#!/bin/bash
NAME=""
IMAGE="bionic"
CPU_MACHINE="2"
DISK_MACHINE="30G"
MEMORY_MACHINE="4G"
# Preconfigured secret to join the cluster (or autogenerated if empty)
CLUSTER_SECRET=""

## Nothing to change after this line
if [ -x "$(command -v multipass.exe)" > /dev/null 2>&1 ]; then
 # Windows
 MULTIPASSCMD="multipass.exe"
elif [ -x "$(command -v multipass)" > /dev/null 2>&1 ]; then
 # Linux/MacOS
 MULTIPASSCMD="multipass"
else
 echo "The multipass binary (multipass or multipass.exe) is not available or not in your \$PATH"
 exit 1
fi

if [ -z $CLUSTER_SECRET ]; then
 CLUSTER_SECRET=$(cat /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1 | tr '[:upper:]' '[:lower:]')
 echo "No cluster secret given, generated secret: ${CLUSTER_SECRET}"
fi

# Check if name is given or create random string
if [ -z $NAME ]; then
    NAME=$(cat /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1 | tr '[:upper:]' '[:lower:]')
    echo "No name given, generated name: ${NAME}"
fi

echo "Creating k3s VM ${NAME}"

# Prepare cloud-init
# Cloud init template
target="/etc/rancher/k3s/registries.yaml"
registry_domain="docker.test"
registry_port=32000
manifests="/var/lib/rancher/k3s/server/manifests"
read -r -d '' CLOUDINIT_TEMPLATE << EOM
#cloud-config
write_files:
- content: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: cert-manager
  path: $manifests/0-cert-manager-namespace.yml
- content: |
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: registry
      namespace: kube-system
    spec:
      chart: stable/docker-registry
      targetNamespace: default
      set:
        persistence.enabled: "true"
        persistence.deleteEnabled: "true"
        service.type: "NodePort"
        service.nodePort: "32000"
  path: $manifests/1-registry.yml
- content: |
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: cert-manager
      namespace: kube-system
    spec:
      chart: cert-manager
      repo: https://charts.jetstack.io
      targetNamespace: cert-manager
      version: v0.15.1
      set:
        installCRDs: "true"
  path: $manifests/2-cert-manager.yml
- content: |
    mirrors:
      "${registry_domain}:${registry_port}":
        endpoint:
          - http://${registry_domain}:${registry_port}
  path: $target
runcmd:
 - '\curl -sfL https://get.k3s.io | K3S_CLUSTER_SECRET=$CLUSTER_SECRET K3S_KUBECONFIG_MODE=644 sh -'
EOM

echo "$CLOUDINIT_TEMPLATE" > "${NAME}-cloud-init.yaml"
echo "Cloud-init is created at ${NAME}-cloud-init.yaml"

echo "Running $MULTIPASSCMD launch --cpus $CPU_MACHINE --disk $DISK_MACHINE --mem $MEMORY_MACHINE $IMAGE --name k3s-server-$NAME --cloud-init ${NAME}-cloud-init.yaml"
$MULTIPASSCMD launch --cpus $CPU_MACHINE --disk $DISK_MACHINE --mem $MEMORY_MACHINE $IMAGE --name k3s-server-$NAME --cloud-init "${NAME}-cloud-init.yaml"
if [ $? -ne 0 ]; then
    echo "There was an error launching the instance"
    exit 1
fi

echo "Checking for server being Ready on k3s-server-${NAME}"
$MULTIPASSCMD exec k3s-server-$NAME -- /bin/bash -c 'while [[ $(sudo k3s kubectl get nodes --no-headers 2>/dev/null | grep -c -v "NotReady") -eq 0 ]]; do echo "."; sleep 2; done'
echo "Node is Ready on k3s-server-${NAME}"

echo "Checking for manifests being insalled on k3s-server-${NAME}"
$MULTIPASSCMD exec k3s-server-$NAME -- /bin/bash -c 'while [[ $(sudo k3s kubectl get pods -n kube-system --no-headers 2>/dev/null | grep "helm-install" | grep -c -v "Completed") -ne 0 ]]; do echo "."; sleep 2; done'
echo "helms are installed on k3s-server-${NAME}"

mkdir -p ~/.kube

function kmerge() {
    KUBECONFIG=~/.kube/config:$1 kubectl config view --flatten > ~/.kube/mergedkub && mv ~/.kube/mergedkub ~/.kube/config
}

SERVER_IP=$($MULTIPASSCMD info k3s-server-$NAME | grep IPv4 | awk '{ print $2 }')
$MULTIPASSCMD copy-files k3s-server-$NAME:/etc/rancher/k3s/k3s.yaml $NAME-kubeconfig-orig.yaml
sed "/^[[:space:]]*server:/ s_:.*_: \"https://$(echo $SERVER_IP | sed -e 's/[[:space:]]//g'):6443\"_" $NAME-kubeconfig-orig.yaml > $NAME-kubeconfig.yaml
sed -i "" "s|name: default|name: k3s-server-$NAME|" $NAME-kubeconfig.yaml
sed -i "" "s|user: default|user: k3s-server-$NAME|" $NAME-kubeconfig.yaml
sed -i "" "s|cluster: default|cluster: k3s-server-$NAME|" $NAME-kubeconfig.yaml
sed -i "" "s|current-context: default|current-context: k3s-server-$NAME|" $NAME-kubeconfig.yaml
echo "k3s setup finished"
kubectl --kubeconfig ${NAME}-kubeconfig.yaml get nodes
kubectl --kubeconfig ${NAME}-kubeconfig.yaml get pods -A
echo "$MULTIPASSCMD exec k3s-server-${NAME} -- sudo k3s kubectl get nodes"
echo "Or use kubectl directly"
echo "kubectl --kubeconfig ${NAME}-kubeconfig.yaml get nodes"
#kmerge ${NAME}-kubeconfig.yaml
#echo "Switch kubectl context to k3s-server-${NAME}"
#kubectl config use-context k3s-server-${NAME}
